# Generated by Django 5.2.1 on 2025-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_attribute_create_attribute_update_product_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Абсолютная ссылка на видео YouTube', verbose_name='YouTube URL'),
        ),
    ]
