# Generated by Django 5.2.1 on 2025-09-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(blank=True, help_text='Автоматически рассчитывается при сохранении', null=True, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена до скидки (если есть скидка)', max_digits=10, null=True, verbose_name='Старая цена'),
        ),
    ]
